version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  deploy:
    executor:
      name: node/default
      tag: lts
    parameters:
      stage:
        description: Stage to deploy to
        type: string
        default: ''
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Deploy service
          command: |
            STAGE=<< parameters.stage >>
            [[ ! -z "$STAGE" ]] || STAGE=${CIRCLE_BRANCH%%/*}
            echo Deploying service to stage $STAGE
            npm run deploy -- --stage $STAGE

workflows:
  version: 2
  test-and-deploy:
    jobs:
      # all
      - node/test:
          version: 'lts'

      # branch
      - deploy:
          name: deploy-branch
          context: env-coaches-nonprod
          requires: [node/test]
          filters: &only-branches
            branches:
              ignore: main

      # main - coaches-sandbox automation
      - deploy:
          name: deploy-coaches-sandbox
          stage: automation
          context: env-coaches-nonprod
          requires: [node/test]
          filters: &only-main
            branches:
              only: main

      # main - coaches-prod automation
      - deploy:
          name: deploy-coaches-prod
          stage: automation
          context: env-coaches-prod
          requires: [deploy-coaches-sandbox]
          filters: *only-main
